export { AspiranteDocumentosPage } from './AspiranteDocumentos'
export { AspiranteLoginPage } from './AspiranteLogin'
export { AdmisionesPage } from './AdmisionesPage'
export { CreditosPage } from './Creditos'
export { HomePage } from './Home'
export { LoginPage } from './Login'
export { MatriculaPage } from './Matricula'
export { SolicitudesPage } from './Solicitudes'
