import { useCallback, useState } from 'react'
import { useParams } from 'react-router-dom'
import { BackButton, ModuleLayout } from '../../components'
import { actualizarLiquidacion, obtenerLiquidacion, obtenerProceso } from '../../modules/matricula-financiera/api'
import { useConsulta, useOperacion } from '../../modules/matricula-financiera/hooks'
import { ajustesActuales, etiquetaEstadoLiquidacion, fechaColombia, formatoMonedaEntrada, normalizarMoneda, puedeEditarFila } from '../../modules/matricula-financiera/rules'
import type { LiquidacionMatricula, ProcesoLiquidacion, PreguntaLiquidacion } from '../../modules/matricula-financiera/types'
import { Aviso, Alertas, Importe } from './FinancieraUi'
import { RespuestasForm } from './RespuestasForm'
import { CertificadoVotacion } from './CertificadoVotacion'
import { LiquidacionActions } from './LiquidacionActions'
import './MatriculaFinancieraPage.css'

export function LiquidacionDetallePage() {
  const params = useParams(); const id = Number(params.liquidacionId); const procesoId = Number(params.procesoId)
  const consulta = useConsulta(useCallback(async (signal: AbortSignal) => {
    if (!Number.isInteger(id) || id < 1 || !Number.isInteger(procesoId) || procesoId < 1) throw new Error('La liquidación solicitada no es válida.')
    const [fila, proceso] = await Promise.all([obtenerLiquidacion(id, signal), obtenerProceso(procesoId, signal)])
    if (fila.procesoId !== procesoId) throw new Error('La liquidación no pertenece a este proceso.')
    return { fila, proceso }
  }, [id, procesoId]))
  return <ModuleLayout title="Detalle de liquidación"><div className="mf-page"><BackButton to={`/matricula/financiera/procesos/${procesoId}`}>Volver al proceso</BackButton><Aviso error={consulta.error} />{consulta.error && <button className="mf-button" onClick={consulta.refresh}>Reintentar consulta</button>}{consulta.loading ? <p role="status">Cargando liquidación…</p> : consulta.data && <Detalle key={JSON.stringify(consulta.data)} {...consulta.data} onChange={consulta.refresh} />}</div></ModuleLayout>
}
function Detalle({ fila, proceso, onChange }: { fila: LiquidacionMatricula; proceso: ProcesoLiquidacion; onChange: () => void }) {
  const op = useOperacion(); const [documentBusy, setDocumentBusy] = useState(false); const [responsesDirty, setResponsesDirty] = useState(false); const [editingResponses, setEditingResponses] = useState(false)
  const busy = op.busy || documentBusy; const initial = ajustesActuales(fila)
  const [ajustes, setAjustes] = useState({ semestre: fila.semestre == null ? '' : String(initial.semestre), ajusteManual: String(initial.ajusteManual), valorFinalManual: initial.valorFinalManual == null ? '' : String(initial.valorFinalManual), observaciones: initial.observaciones ?? '' })
  const updateMoney = (field: 'ajusteManual' | 'valorFinalManual', raw: string) => { const value = normalizarMoneda(raw, field === 'ajusteManual'); if (value !== null) setAjustes(current => ({ ...current, [field]: value })) }
  const ajustesDirty = ajustes.semestre !== String(initial.semestre) || ajustes.ajusteManual !== String(initial.ajusteManual) || ajustes.valorFinalManual !== (initial.valorFinalManual == null ? '' : String(initial.valorFinalManual)) || ajustes.observaciones !== (initial.observaciones ?? '')
  const allowed = (accion: Parameters<typeof puedeEditarFila>[2]) => puedeEditarFila(proceso.estado, fila, accion)
  const preguntas: PreguntaLiquidacion[] = [
    { clave: 'entregoTrabajoGrado', texto: '¿Entregó el trabajo de grado (Acuerdo 048 de 2024)?', aplica: fila.tipoEstudiante === 'VIGENTE' }, { clave: 'cumLaude', texto: '¿Tiene beneficio de matrícula por Cum Laude?', aplica: fila.tipoEstudiante === 'VIGENTE' },
    { clave: 'certificadoVotacion', texto: '¿Tiene certificado de votación vigente?', aplica: true }, { clave: 'deseaSalud', texto: '¿Desea el pago de derechos de salud UIS?', aplica: true },
  ]
  const saveAdjustments = async () => { await op.run(async () => { await actualizarLiquidacion(fila.id, 'ajustes', { semestre: Number(ajustes.semestre), promocion: initial.promocion, ajusteManual: Number(ajustes.ajusteManual), valorFinalManual: ajustes.valorFinalManual === '' ? null : Number(ajustes.valorFinalManual), observaciones: ajustes.observaciones.trim() || null }); onChange() }, 'Correcciones guardadas.') }
  return <><header><h1>{fila.codigoEstudiante} · {fila.nombreCompleto || 'Nombre no disponible'}</h1></header><Aviso error={op.error} message={op.message} />
    <section className="mf-card"><div className="mf-review-status"><span>Estado de la liquidación</span><strong className={`mf-badge mf-badge--${fila.estado.toLowerCase()}`}>{etiquetaEstadoLiquidacion(fila.estado)}</strong></div><h2>Revisión del caso</h2><Alertas alertas={fila.alertas.filter(alerta => alerta !== 'PROMOCION_FALTANTE')} />{fila.motivoExclusion && <p>Motivo de exclusión: {fila.motivoExclusion}</p>}<dl className="mf-values"><div><dt>Programa académico</dt><dd>{fila.programa}</dd></div><div><dt>Tipo de estudiante</dt><dd>{fila.tipoEstudiante}</dd></div><div><dt>Periodo</dt><dd>{proceso.periodo}</dd></div><div><dt>Semestre</dt><dd>{fila.semestre ?? 'Sin calcular'}</dd></div><div><dt>Origen de respuesta</dt><dd>{fila.origenRespuesta ?? 'Sin respuesta'}</dd></div>{Object.entries({ 'Solicitud enviada': fila.fechaEnvioSolicitud, 'Último recordatorio': fila.fechaUltimoRecordatorio, 'Respuesta recibida': fila.fechaRespuesta, 'Marcada liquidada': fila.fechaLiquidada }).map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{fechaColombia(value)}</dd></div>)}</dl></section>
    <section className="mf-card"><div className="mf-section-heading"><div><h2>Respuestas y respaldo de coordinación</h2><p>{editingResponses ? 'Modo de edición activo.' : 'Consulta las respuestas registradas y su respaldo.'}</p></div>{allowed('respuestas') && (editingResponses ? <button className="mf-button mf-button--secondary" type="button" disabled={busy} onClick={() => { setEditingResponses(false); setResponsesDirty(false) }}>Cancelar edición</button> : <button className="mf-button mf-button--secondary" type="button" onClick={() => setEditingResponses(true)}>Editar respuestas</button>)}</div>{editingResponses && <p className="mf-notice" role="status"><strong>Estás editando en nombre del estudiante.</strong> Verifica la información antes de registrar cualquier cambio.</p>}<RespuestasForm key={editingResponses ? 'editing' : 'viewing'} respuestas={fila.respuestas} preguntas={preguntas} tipo={fila.tipoEstudiante} coordinacion observaciones={fila.observaciones} editable={editingResponses && allowed('respuestas')} busy={busy} onDirtyChange={setResponsesDirty} renderCertificado={onValidChange => <CertificadoVotacion embedded liquidacionId={fila.id} editable={editingResponses && proceso.estado !== 'PUBLICADO' && !op.busy} onBusyChange={setDocumentBusy} onValidChange={onValidChange} onChange={onChange} />} onSave={async body => { const saved = await op.run(async () => { await actualizarLiquidacion(fila.id, 'respuestas', body); onChange() }); if (saved !== false) setEditingResponses(false); return saved }} />{fila.estado === 'LIQUIDADA' && proceso.estado !== 'PUBLICADO' && <p>Desmarca la liquidación para corregir respuestas.</p>}</section>
    <section className="mf-card"><h2>Cálculo recibido del sistema</h2><dl className="mf-values"><Importe titulo="Matrícula" valor={fila.calculo?.valorMatricula} /><Importe titulo="Derechos académicos" valor={fila.calculo?.valorDerechos} /><Importe titulo="Descuento trabajo de grado" valor={fila.calculo?.descuentoTrabajoGrado} /><Importe titulo="Descuento Cum Laude" valor={fila.calculo?.descuentoCumLaude} /><Importe titulo="Descuento votación" valor={fila.calculo?.descuentoVotacion} /><Importe titulo="Salud" valor={fila.calculo?.valorSalud} /><Importe titulo="Total calculado" valor={fila.calculo?.totalCalculado} /><Importe titulo="Ajuste autorizado" valor={fila.ajusteManual} />{fila.valorFinalManual != null && <Importe titulo="Total autorizado manualmente" valor={fila.valorFinalManual} />}<Importe titulo="Total final" valor={fila.totalFinal} /></dl>
      <details className="mf-correction"><summary>Corregir cálculo</summary><form onSubmit={e => { e.preventDefault(); void saveAdjustments() }}><p>El cálculo definitivo siempre viene del servidor. Cerrar este panel no borra lo escrito.</p>{fila.estado === 'LIQUIDADA' && <p>Desmarca la liquidación antes de modificar valores confirmados.</p>}<fieldset disabled={busy || !allowed('ajustes')} className="mf-form mf-fieldset"><label>Semestre<input type="number" min="1" step="1" required value={ajustes.semestre} onChange={e => setAjustes({ ...ajustes, semestre: e.target.value })} /></label><label>Valor a sumar o restar al cálculo (COP)<input inputMode="decimal" required value={formatoMonedaEntrada(ajustes.ajusteManual)} onChange={e => updateMoney('ajusteManual', e.target.value)} /><small>Los valores positivos aumentan el total; los negativos lo reducen. Se admiten hasta cuatro decimales.</small></label><label>Total autorizado manualmente (COP, opcional)<input inputMode="decimal" value={formatoMonedaEntrada(ajustes.valorFinalManual)} onChange={e => updateMoney('valorFinalManual', e.target.value)} /><small>Sustituye el total calculado y su ajuste. Dejarlo vacío retira esa sustitución.</small></label><label>Motivo del ajuste (opcional)<textarea value={ajustes.observaciones} onChange={e => setAjustes({ ...ajustes, observaciones: e.target.value })} /></label>{allowed('ajustes') && <button className="mf-button" type="submit">{busy ? 'Guardando…' : 'Guardar correcciones'}</button>}</fieldset></form></details>
    </section>
    <section className="mf-card"><h2>Estado de la liquidación</h2>{proceso.estado === 'PUBLICADO' ? <p>El proceso está publicado. Solo se permite consulta.</p> : <><p>Confirma únicamente después de registrar la liquidación en PUTTY.</p>{(responsesDirty || ajustesDirty) && <p className="mf-notice">Guarda las respuestas y correcciones pendientes antes de confirmar.</p>}<LiquidacionActions fila={fila} proceso={proceso} cambiosSinGuardar={responsesDirty || ajustesDirty} onChange={onChange} />{fila.estado === 'RESPONDIDA' && fila.totalFinal == null && <p>Necesitas un total válido antes de confirmar; el valor cero sí es válido.</p>}</>}</section>
  </>
}
