import { useCallback, useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { ModuleLayout } from '../../components'
import { ejecutarAccionProceso, exportarProceso, listarLiquidaciones, obtenerProceso, actualizarLiquidacion, publicarProceso } from '../../modules/matricula-financiera/api'
import type { EstadoLiquidacion, LiquidacionMatricula, ProcesoLiquidacion } from '../../modules/matricula-financiera/types'
import { etiquetaResumen, puedeEjecutarAccion } from '../../modules/matricula-financiera/flow'
import './MatriculaFinancieraPage.css'

const money = (value?: number | null) => value == null ? 'Sin calcular' : new Intl.NumberFormat('es-CO', { style: 'currency', currency: 'COP', maximumFractionDigits: 4 }).format(value)
export const ProcesoLiquidacionPage = () => {
  const id = Number(useParams().procesoId); const [proceso,setProceso]=useState<ProcesoLiquidacion|null>(null); const [rows,setRows]=useState<LiquidacionMatricula[]>([]); const [error,setError]=useState(''); const [busy,setBusy]=useState(''); const [estado,setEstado]=useState<EstadoLiquidacion|''>(''); const [texto,setTexto]=useState(''); const [fechaPago,setFechaPago]=useState('')
  const load=useCallback(async()=>{try{setError('');const [p,r]=await Promise.all([obtenerProceso(id),listarLiquidaciones(id,{estado,texto})]);setProceso(p);setRows(r)}catch(e){setError(e instanceof Error?e.message:'No fue posible cargar el proceso')}},[id,estado,texto])
  useEffect(()=>{void load()},[load])
  const action=async(name:'convocar'|'enviarSolicitudes'|'enviarRecordatorio'|'cerrar'|'reabrir'|'recalcular')=>{setBusy(name);try{await ejecutarAccionProceso(id,name);await load()}catch(e){setError(e instanceof Error?e.message:'No fue posible completar la acción')}finally{setBusy('')}}
  const publish=async(event:React.FormEvent)=>{event.preventDefault();setBusy('publicar');try{await publicarProceso(id,fechaPago);setFechaPago('');await load()}catch(e){setError(e instanceof Error?e.message:'No fue posible publicar el proceso')}finally{setBusy('')}}
  const canEdit=proceso?.estado!=='PUBLICADO'; const allowed={convocar:puedeEjecutarAccion(proceso?.estado,'convocar'),send:puedeEjecutarAccion(proceso?.estado,'enviarSolicitudes'),remind:puedeEjecutarAccion(proceso?.estado,'enviarRecordatorio'),close:puedeEjecutarAccion(proceso?.estado,'cerrar'),reopen:puedeEjecutarAccion(proceso?.estado,'reabrir'),recalc:puedeEjecutarAccion(proceso?.estado,'recalcular'),publish:puedeEjecutarAccion(proceso?.estado,'publicar')}
  return <ModuleLayout title="Tablero de matrícula financiera"><div className="mf-page"> <Link to="/matricula/financiera" className="mf-back">← Volver a procesos</Link>{error&&<div className="mf-notice mf-notice--error">{error}</div>}{proceso&&<>
    <header className="mf-page__intro"><div><span className={`mf-badge mf-badge--${proceso.estado.toLowerCase()}`}>{proceso.estado}</span><h1>Liquidaciones · {proceso.periodo}</h1><p>Respuesta hasta {proceso.fechaLimiteRespuesta} · SMMLV {money(proceso.valorSmmlv)}</p></div><button className="mf-button mf-button--secondary" onClick={()=>void exportarProceso(id).catch(e=>setError(e.message))}>↓ Exportar Excel</button></header>
    <section className="mf-summary" aria-label="Resumen del proceso">{Object.entries(proceso.resumen).map(([key,value])=><div className="mf-card" key={key}><strong>{value}</strong><span>{etiquetaResumen(key)}</span></div>)}</section>
    <div className="mf-actions"><button disabled={!allowed.convocar||!!busy} onClick={()=>void action('convocar')} className="mf-button">＋ Convocar</button><button disabled={!allowed.send||!!busy} onClick={()=>void action('enviarSolicitudes')} className="mf-button">✉ Enviar solicitudes</button><button disabled={!allowed.remind||!!busy} onClick={()=>void action('enviarRecordatorio')} className="mf-button mf-button--secondary">Recordatorio</button><button disabled={!allowed.recalc||!!busy} onClick={()=>void action('recalcular')} className="mf-button mf-button--secondary">↻ Recalcular</button><button disabled={!allowed.close||!!busy} onClick={()=>void action('cerrar')} className="mf-button mf-button--secondary">Cerrar</button><button disabled={!allowed.reopen||!!busy} onClick={()=>void action('reabrir')} className="mf-button mf-button--secondary">Reabrir</button></div>
    {allowed.publish&&<form className="mf-publish mf-card" onSubmit={publish}><div><h2>Publicar liquidaciones</h2><p>Esta acción hace visibles los valores al estudiante. Confirma primero que no queden casos por revisar.</p></div><label>Fecha límite de pago<input required type="date" value={fechaPago} onChange={e=>setFechaPago(e.target.value)}/></label><button disabled={!!busy} className="mf-button" type="submit">Publicar resultados</button></form>}
    <div className="mf-filters"><input aria-label="Buscar estudiante" placeholder="Código, nombre o programa" value={texto} onChange={e=>setTexto(e.target.value)}/><select aria-label="Estado" value={estado} onChange={e=>setEstado(e.target.value as EstadoLiquidacion|'')}><option value="">Todos los estados</option><option value="PENDIENTE_RESPUESTA">Pendiente</option><option value="RESPONDIDA">Respondida</option><option value="LIQUIDADA">Liquidada</option><option value="NO_LIQUIDAR">No liquidar</option></select></div>
    <div className="mf-table-wrap"><table className="mf-table"><thead><tr><th>Estudiante</th><th>Programa</th><th>Estado</th><th>Semestre</th><th>Total</th><th>Alertas</th><th>Acción</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><b>{row.codigoEstudiante}</b><small>{row.nombreCompleto||'Nombre no disponible'}</small></td><td>{row.programa}</td><td><span className={`mf-badge mf-badge--${row.estado.toLowerCase()}`}>{row.estado.replaceAll('_',' ')}</span></td><td>{row.semestre??'—'}</td><td>{money(row.totalFinal)}</td><td>{row.alertas.map(a=><span className="mf-alert" key={a}>{a.replaceAll('_',' ')}</span>)}</td><td>{row.estado==='RESPONDIDA'&&canEdit?<button className="mf-text-button" onClick={()=>void actualizarLiquidacion(row.id,'liquidada',{liquidada:true}).then(load).catch(e=>setError(e.message))}>Marcar liquidada</button>:row.estado==='LIQUIDADA'&&canEdit?<button className="mf-text-button" onClick={()=>void actualizarLiquidacion(row.id,'liquidada',{liquidada:false}).then(load).catch(e=>setError(e.message))}>Desmarcar</button>:'—'}</td></tr>)}</tbody></table></div>
  </>}</div></ModuleLayout>
}
